version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=school_registration
      - JWT_SECRET=your-super-secret-key
      - JWT_EXPIRATION=1h
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - school-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=school_registration
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school-network

volumes:
  postgres_data:

networks:
  school-network:
    driver: bridge 